name: Terraform Plan (dev)

on:
  pull_request:
    paths:
      - 'modules/**'
      - 'environments/dev/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: terraform-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: dev

    env:
      TF_WORKING_DIR: environments/dev
      TF_PLUGIN_CACHE_DIR: ${{github.workspace}}/.terraform.d/plugin-cache
      TF_TERRAFORM_DIR: .terraform
      TF_INPUT: false
      TF_IN_AUTOMATION: true

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.5

      - name: Create Terraform plugin cache dir
        run: mkdir -p ${{ env.TF_PLUGIN_CACHE_DIR }}

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Create Terraform .terraform dir
        run: mkdir -p ${{ env.TF_WORKING_DIR }}/${{ env.TF_TERRAFORM_DIR }}

      - name: Cache Terraform working dir
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_WORKING_DIR }}/${{ env.TF_TERRAFORM_DIR }}
          key: terraform-dir-${{ runner.os }}-${{ hashFiles('environments/dev/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-dir-${{ runner.os }}-

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Format
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan -no-color -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}/tfplan

      - name: Comment Terraform Plan
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ${{ env.TF_WORKING_DIR }}/plan.txt
