name: Terraform Drift Detection (dev)

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-dev
  cancel-in-progress: true

jobs:

  drift:
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: environments/dev
      TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
      TF_INPUT: false
      TF_IN_AUTOMATION: true
      TF_VAR_ssh_allowed_ip: ${{ vars.MY_PUBLIC_IP }}

    steps:

      - uses: actions/checkout@v4

      - uses: ./.github/actions/terraform-setup
        with:
          working_dir: environments/dev
          aws_role: ${{ vars.AWS_TERRAFORM_ROLE_ARN }}
          aws_region: ${{ vars.AWS_REGION }}

      - name: Terraform Plan (drift detection)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false -detailed-exitcode
