name: Terraform Drift Detection (dev)

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-dev
  cancel-in-progress: true

jobs:

  drift:
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: environments/dev
      TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
      TF_INPUT: false
      TF_IN_AUTOMATION: true
      TF_VAR_ssh_allowed_ip: ${{ vars.MY_PUBLIC_IP }}

    steps:

      - uses: actions/checkout@v4

      - uses: ./.github/actions/terraform-setup
        with:
          working_dir: environments/dev
          aws_role: ${{ vars.AWS_TERRAFORM_ROLE_ARN }}
          aws_region: ${{ vars.AWS_REGION }}

      - name: Terraform Plan (drift detection)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          set +e

          terraform plan -input=false -no-color -detailed-exitcode > plan.txt
          exitcode=$?

          echo "## Terraform Drift Detection" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Environment:** dev" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ $exitcode -eq 0 ]; then
            echo "✅ No drift detected." | tee -a $GITHUB_STEP_SUMMARY

          elif [ $exitcode -eq 2 ]; then
            echo "⚠️ Drift detected!" | tee -a $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Terraform Plan" >> $GITHUB_STEP_SUMMARY
            echo '```diff' >> $GITHUB_STEP_SUMMARY
            grep -E "Plan:" plan.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            exit 1

          else
            echo "❌ Terraform error during drift detection." | tee -a $GITHUB_STEP_SUMMARY
            exit 1
          fi
