name: Terraform Drift Detection (dev)

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  drift:
    runs-on: ubuntu-latest
    environment: dev

    env:
      TF_WORKING_DIR: environments/dev
      TF_PLUGIN_CACHE_DIR: ${{github.workspace}}/.terraform.d/plugin-cache
      TF_TERRAFORM_DIR: .terraform
      TF_INPUT: false
      TF_IN_AUTOMATION: true
      TF_VAR_ssh_allowed_ip: ${{ vars.MY_PUBLIC_IP }}

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.5

      - name: Create Terraform plugin cache dir
        run: mkdir -p ${{ env.TF_PLUGIN_CACHE_DIR }}

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Create Terraform .terraform dir
        run: mkdir -p ${{ env.TF_WORKING_DIR }}/${{ env.TF_TERRAFORM_DIR }}

      - name: Cache Terraform working dir
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_WORKING_DIR }}/${{ env.TF_TERRAFORM_DIR }}
          key: terraform-dir-${{ runner.os }}-${{ hashFiles('environments/dev/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-dir-${{ runner.os }}-

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Plan (drift detection)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -detailed-exitcode
