name: Terraform Destroy (dev)

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type DESTROY to confirm"
        required: true

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-destroy-dev
  cancel-in-progress: false

jobs:
  destroy:
    if: github.event.inputs.confirm_destroy == 'DESTROY'
    runs-on: ubuntu-latest
    environment: dev

    env:
      TF_WORKING_DIR: environments/dev
      TF_PLUGIN_CACHE_DIR: $HOME/.terraform.d/plugin-cache

    steps:

      - uses: actions/checkout@v4

      - name: Create Terraform plugin cache dir
        run: mkdir -p ~/.terraform.d/plugin-cache

      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.5

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Plan Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -destroy

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve
